export const LangCodesComplete = [
  { n: "Acholi", cc: "ug", l: "ach-UG" },
  { n: "Afar", cc: "er", l: "aa-ER" },
  { n: "Afrikaans", cc: "za", l: "af-ZA" },
  { n: "Akan", cc: "gh", l: "ak-GH" },
  { n: "Albanian", cc: "al", l: "sq-AL" },
  { n: "Amharic", cc: "et", l: "am-ET" },
  { n: "Arabic", cc: "jo", l: "ar" },
  { n: "Arabic, Bahrain", cc: "bh", l: "ar-BH" },
  { n: "Arabic, Egypt", cc: "eg", l: "ar-EG" },
  { n: "Arabic, SaudiArabia", cc: "sa", l: "ar-SA" },
  { n: "Arabic, Yemen", cc: "ye", l: "ar-YE" },
  { n: "Aragonese", cc: "es", l: "an-ES" },
  { n: "Armenian", cc: "am", l: "hy-AM" },
  { n: "Arpitan", cc: "it", l: "frp-IT" },
  { n: "Assamese", cc: "in", l: "as-IN" },
  { n: "Asturian", cc: "es", l: "ast-ES" },
  { n: "Atayal", cc: "tw", l: "tay-TW" },
  { n: "Avaric", cc: "ru", l: "av-DA" },
  { n: "Avestan", cc: "ir", l: "ae-IR" },
  { n: "Aymara", cc: "bo", l: "ay-BO" },
  { n: "Azerbaijani", cc: "az", l: "az-AZ" },
  { n: "Balinese", cc: "id", l: "ban-ID" },
  { n: "Balochi", cc: "pk", l: "bal-BA" },
  { n: "Bambara", cc: "ml", l: "bm-ML" },
  { n: "Bashkir", cc: "ru", l: "ba-RU" },
  { n: "Basque", cc: "es", l: "eu-ES" },
  { n: "Belarusian", cc: "by", l: "be-BY" },
  { n: "Bengali", cc: "bn", l: "bn-BD" },
  { n: "Bengali, India", cc: "in", l: "bn-IN" },
  { n: "Berber", cc: "dz", l: "ber-DZ" },
  { n: "Bihari", cc: "in", l: "bh-IN" },
  { n: "Birifor", cc: "bf", l: "bfo-BF" },
  { n: "Bislama", cc: "vu", l: "bi-VU" },
  { n: "Bosnian", cc: "ba", l: "bs-BA" },
  { n: "Breton", cc: "fr", l: "br-FR" },
  { n: "Bulgarian", cc: "bg", l: "bg-BG" },
  { n: "Burmese", cc: "mm", l: "my-MM" },
  { n: "Catalan", cc: "es", l: "ca-ES" },
  { n: "Cebuano", cc: "ph", l: "ceb-PH" },
  { n: "Chamorro", cc: "gu", l: "ch-GU" },
  { n: "Chechen", cc: "ru", l: "ce-CE" },
  { n: "Chewa", cc: "mw", l: "ny-MW" },
  { n: "ChineseSimplified", cc: "cn", l: "zh-CN" },
  { n: "ChineseTraditional", cc: "tw", l: "zh-TW" },
  { n: "ChineseTraditional, HongKong", cc: "hk", l: "zh-HK" },
  { n: "ChineseTraditional, Macau", cc: "mo", l: "zh-MO" },
  { n: "ChineseTraditional, Singapore", cc: "sg", l: "zh-SG" },
  { n: "Chuvash", cc: "ru", l: "cv-CU" },
  { n: "Cornish", cc: "gb", l: "kw-GB" },
  { n: "Corsican", cc: "fr", l: "co-FR" },
  { n: "Cree", cc: "ca", l: "cr-NT" },
  { n: "Croatian", cc: "hr", l: "hr-HR" },
  { n: "Czech", cc: "cz", l: "cs-CZ" },
  { n: "Danish", cc: "dk", l: "da-DK" },
  { n: "Dari", cc: "af", l: "fa-AF" },
  { n: "Dhivehi", cc: "mv", l: "dv-MV" },
  { n: "Dutch", cc: "nl", l: "nl-NL" },
  { n: "Dutch, Belgium", cc: "be", l: "nl-BE" },
  { n: "Dutch, Surin", cc: "sr", l: "nl-SR" },
  { n: "Dzongkha", cc: "bt", l: "dz-BT" },
  { n: "English", cc: "us", l: "en" },
  { n: "English(upsidedown)", cc: "us", l: "en-UD" },
  { n: "English, Arabia", cc: "ae", l: "en-AR" },
  { n: "English, Australia", cc: "au", l: "en-AU" },
  { n: "English, Belize", cc: "bz", l: "en-BZ" },
  { n: "English, Canada", cc: "ca", l: "en-CA" },
  { n: "English, Caribbean", cc: "us", l: "en-CB" },
  { n: "English, China", cc: "cn", l: "en-CN" },
  { n: "English, Denmark", cc: "dk", l: "en-DK" },
  { n: "English, HongKong", cc: "hk", l: "en-HK" },
  { n: "English, India", cc: "in", l: "en-IN" },
  { n: "English, Indonesia", cc: "id", l: "en-ID" },
  { n: "English, Ireland", cc: "ie", l: "en-IE" },
  { n: "English, Jamaica", cc: "jm", l: "en-JM" },
  { n: "English, Malaysia", cc: "my", l: "en-MY" },
  { n: "English, NewZealand", cc: "nz", l: "en-NZ" },
  { n: "English, Norway", cc: "no", l: "en-NO" },
  { n: "English, Philippines", cc: "ph", l: "en-PH" },
  { n: "English, PuertoRico", cc: "pr", l: "en-PR" },
  { n: "English, Singapore", cc: "sg", l: "en-SG" },
  { n: "English, SouthAfrica", cc: "za", l: "en-ZA" },
  { n: "English, Sweden", cc: "se", l: "en-SE" },
  { n: "English, UnitedKingdom", cc: "gb", l: "en-GB" },
  { n: "English, UnitedStates", cc: "us", l: "en-US" },
  { n: "English, Zimbabwe", cc: "zw", l: "en-ZW" },
  { n: "Esperanto", cc: "uy", l: "eo-UY" },
  { n: "Estonian", cc: "ee", l: "et-EE" },
  { n: "Faroese", cc: "fo", l: "fo-FO" },
  { n: "Fijian", cc: "fj", l: "fj-FJ" },
  { n: "Filipino", cc: "ph", l: "fil-PH" },
  { n: "Finnish", cc: "fi", l: "fi-FI" },
  { n: "Flemish", cc: "be", l: "vls-BE" },
  { n: "Franconian", cc: "de", l: "fra-DE" },
  { n: "French", cc: "fr", l: "fr-FR" },
  { n: "French, Belgium", cc: "be", l: "fr-BE" },
  { n: "French, Canada", cc: "ca", l: "fr-CA" },
  { n: "French, Luxembourg", cc: "lu", l: "fr-LU" },
  { n: "French, Quebec", cc: "ca", l: "fr-QC" },
  { n: "French, Switzerland", cc: "ch", l: "fr-CH" },
  { n: "Frisian", cc: "nl", l: "fy-NL" },
  { n: "Friulian", cc: "it", l: "fur-IT" },
  { n: "Fula", cc: "za", l: "ff-ZA" },
  { n: "Ga", cc: "gh", l: "gaa-GH" },
  { n: "Galician", cc: "es", l: "gl-ES" },
  { n: "Georgian", cc: "ge", l: "ka-GE" },
  { n: "German", cc: "de", l: "de-DE" },
  { n: "German, Austria", cc: "at", l: "de-AT" },
  { n: "German, Belgium", cc: "be", l: "de-BE" },
  { n: "German, Liechtenstein", cc: "li", l: "de-LI" },
  { n: "German, Luxembourg", cc: "lu", l: "de-LU" },
  { n: "German, Switzerland", cc: "ch", l: "de-CH" },
  { n: "Gothic", cc: "de", l: "got-DE" },
  { n: "Greek", cc: "gr", l: "el-GR" },
  { n: "Greek, Cyprus", cc: "cy", l: "el-CY" },
  { n: "Greenlandic", cc: "dk", l: "kl-GL" },
  { n: "Guarani", cc: "py", l: "gn-PY" },
  { n: "Gujarati", cc: "in", l: "gu-IN" },
  { n: "HaitianCreole", cc: "ht", l: "ht-HT" },
  { n: "Hausa", cc: "ng", l: "ha-HG" },
  { n: "Hawaiian", cc: "us", l: "haw-US" },
  { n: "Hebrew", cc: "il", l: "he-IL" },
  { n: "Herero", cc: "na", l: "hz-NA" },
  { n: "Hiligaynon", cc: "ph", l: "hil-PH" },
  { n: "Hindi", cc: "in", l: "hi-IN" },
  { n: "HiriMotu", cc: "pg", l: "ho-PG" },
  { n: "Hmong", cc: "cn", l: "hmn-CN" },
  { n: "Hungarian", cc: "hu", l: "hu-HU" },
  { n: "Icelandic", cc: "is", l: "is-IS" },
  { n: "Igbo", cc: "ng", l: "ig-NG" },
  { n: "Ilokano", cc: "ph", l: "ilo-PH" },
  { n: "Indonesian", cc: "id", l: "id-ID" },
  { n: "Inuktitut", cc: "ca", l: "iu-NU" },
  { n: "Irish", cc: "ie", l: "ga-IE" },
  { n: "Italian", cc: "it", l: "it-IT" },
  { n: "Italian, Switzerland", cc: "ch", l: "it-CH" },
  { n: "Japanese", cc: "jp", l: "ja-JP" },
  { n: "Javanese", cc: "id", l: "jv-ID" },
  { n: "K'iche'", cc: "gt", l: "quc-GT" },
  { n: "Kabyle", cc: "dz", l: "kab-KAB" },
  { n: "Kannada", cc: "in", l: "kn-IN" },
  { n: "Kapampangan", cc: "ph", l: "pam-PH" },
  { n: "Kashmiri", cc: "in", l: "ks-IN" },
  { n: "Kashmiri, Pakistan", cc: "pk", l: "ks-PK" },
  { n: "Kashubian", cc: "pl", l: "csb-PL" },
  { n: "Kazakh", cc: "kz", l: "kk-KZ" },
  { n: "Khmer", cc: "kh", l: "km-KH" },
  { n: "Kinyarwanda", cc: "rw", l: "rw-RW" },
  { n: "Komi", cc: "ru", l: "kv-KO" },
  { n: "Kongo", cc: "cd", l: "kg-CG" },
  { n: "Konkani", cc: "in", l: "kok-IN" },
  { n: "Korean", cc: "kr", l: "ko-KR" },
  { n: "Kurdish", cc: "ir", l: "ku-TR" },
  { n: "Kurmanji(Kurdish)", cc: "ir", l: "kmr-TR" },
  { n: "Kwanyama", cc: "ao", l: "kj-AO" },
  { n: "Kyrgyz", cc: "kg", l: "ky-KG" },
  { n: "Lao", cc: "la", l: "lo-LA" },
  { n: "Latin", cc: "va", l: "la-LA" },
  { n: "Latvian", cc: "lv", l: "lv-LV" },
  { n: "Ligurian", cc: "it", l: "lij-IT" },
  { n: "Limburgish", cc: "nl", l: "li-LI" },
  { n: "Lingala", cc: "cd", l: "ln-CD" },
  { n: "Lithuanian", cc: "lt", l: "lt-LT" },
  { n: "LowGerman", cc: "de", l: "nds-DE" },
  { n: "LowerSorbian", cc: "de", l: "dsb-DE" },
  { n: "Luganda", cc: "ug", l: "lg-UG" },
  { n: "Luhya", cc: "ke", l: "luy-KE" },
  { n: "Luxembourgish", cc: "lu", l: "lb-LU" },
  { n: "Macedonian", cc: "mk", l: "mk-MK" },
  { n: "Maithili", cc: "in", l: "mai-IN" },
  { n: "Malagasy", cc: "mg", l: "mg-MG" },
  { n: "Malay", cc: "my", l: "ms-MY" },
  { n: "Malay, Brunei", cc: "bn", l: "ms-BN" },
  { n: "Malayalam", cc: "in", l: "ml-IN" },
  { n: "Maltese", cc: "mt", l: "mt-MT" },
  { n: "Manx", cc: "gb", l: "gv-IM" },
  { n: "Maori", cc: "nz", l: "mi-NZ" },
  { n: "Mapudungun", cc: "cl", l: "arn-CL" },
  { n: "Marathi", cc: "in", l: "mr-IN" },
  { n: "Marshallese", cc: "mh", l: "mh-MH" },
  { n: "Mohawk", cc: "ca", l: "moh-CA" },
  { n: "Mongolian", cc: "mn", l: "mn-MN" },
  { n: "Montenegrin(Cyrillic)", cc: "me", l: "sr-Cyrl-ME" },
  { n: "Montenegrin(Latin)", cc: "me", l: "me-ME" },
  { n: "Mossi", cc: "bf", l: "mos-MOS" },
  { n: "Nauru", cc: "nr", l: "na-NR" },
  { n: "Ndonga", cc: "na", l: "ng-NA" },
  { n: "Nepali", cc: "np", l: "ne-NP" },
  { n: "Nepali, India", cc: "in", l: "ne-IN" },
  { n: "NigerianPidgin", cc: "ng", l: "pcm-NG" },
  { n: "NorthernSami", cc: "no", l: "se-NO" },
  { n: "NorthernSotho", cc: "za", l: "ns-ZA" },
  { n: "Norwegian", cc: "no", l: "no-NO" },
  { n: "Norwegian Bokmal", cc: "no", l: "nb-NO" },
  { n: "Norwegian Nynorsk", cc: "no", l: "nn-NO" },
  { n: "Occitan", cc: "fr", l: "oc-FR" },
  { n: "Odia", cc: "in", l: "or-IN" },
  { n: "Ojibwe", cc: "ca", l: "oj-CA" },
  { n: "Oromo", cc: "et", l: "om-ET" },
  { n: "Ossetian", cc: "ru", l: "os-SE" },
  { n: "Pali", cc: "in", l: "pi-IN" },
  { n: "Papiamento", cc: "aw", l: "pap-PAP" },
  { n: "Pashto", cc: "af", l: "ps-AF" },
  { n: "Persian", cc: "ir", l: "fa-IR" },
  { n: "PirateEnglish", cc: "gb", l: "en-PT" },
  { n: "Polish", cc: "pl", l: "pl-PL" },
  { n: "Portuguese", cc: "pt", l: "pt-PT" },
  { n: "Portuguese, Brazilian", cc: "br", l: "pt-BR" },
  { n: "Punjabi", cc: "in", l: "pa-IN" },
  { n: "Punjabi, Pakistan", cc: "pk", l: "pa-PK" },
  { n: "Quechua", cc: "pe", l: "qu-PE" },
  { n: "Romanian", cc: "ro", l: "ro-RO" },
  { n: "Romansh", cc: "ch", l: "rm-CH" },
  { n: "Rundi", cc: "bi", l: "rn-BI" },
  { n: "Russian", cc: "ru", l: "ru-RU" },
  { n: "Russian, Belarus", cc: "by", l: "ru-BY" },
  { n: "Russian, Moldova", cc: "md", l: "ru-MD" },
  { n: "Russian, Ukraine", cc: "ua", l: "ru-UA" },
  { n: "Rusyn", cc: "ua", l: "ry-UA" },
  { n: "Sakha", cc: "ru", l: "sah-SAH" },
  { n: "Sango", cc: "cf", l: "sg-CF" },
  { n: "Sanskrit", cc: "in", l: "sa-IN" },
  { n: "Santali", cc: "in", l: "sat-IN" },
  { n: "Sardinian", cc: "it", l: "sc-IT" },
  { n: "Scots", cc: "gb", l: "sco-GB" },
  { n: "ScottishGaelic", cc: "gb", l: "gd-GB" },
  { n: "Serbian(Cyrillic)", cc: "rs", l: "sr-SP" },
  { n: "Serbian(Latin)", cc: "rs", l: "sr-CS" },
  { n: "Serbo-Croatian", cc: "hr", l: "sh-HR" },
  { n: "SeychelloisCreole", cc: "sc", l: "crs-SC" },
  { n: "Shona", cc: "zw", l: "sn-ZW" },
  { n: "SichuanYi", cc: "cn", l: "ii-CN" },
  { n: "Sindhi", cc: "pk", l: "sd-PK" },
  { n: "Sinhala", cc: "lk", l: "si-LK" },
  { n: "Slovak", cc: "sk", l: "sk-SK" },
  { n: "Slovenian", cc: "si", l: "sl-SI" },
  { n: "Somali", cc: "so", l: "so-SO" },
  { n: "Songhay", cc: "za", l: "son-ZA" },
  { n: "Sorani(Kurdish)", cc: "ir", l: "ckb-IR" },
  { n: "Southern Ndebele", cc: "za", l: "nr-ZA" },
  { n: "Southern Sami", cc: "no", l: "sma-NO" },
  { n: "Southern Sotho", cc: "za", l: "st-ZA" },
  { n: "Spanish", cc: "es", l: "es-ES" },
  { n: "Spanish(Modern)", cc: "es", l: "es-EM" },
  { n: "Spanish, Argentina", cc: "ar", l: "es-AR" },
  { n: "Spanish, Bolivia", cc: "bo", l: "es-BO" },
  { n: "Spanish, Chile", cc: "cl", l: "es-CL" },
  { n: "Spanish, Colombia", cc: "co", l: "es-CO" },
  { n: "Spanish, CostaRica", cc: "cr", l: "es-CR" },
  { n: "Spanish, DominicanRepublic", cc: "do", l: "es-DO" },
  { n: "Spanish, Ecuador", cc: "ec", l: "es-EC" },
  { n: "Spanish, ElSalvador", cc: "sv", l: "es-SV" },
  { n: "Spanish, Guatemala", cc: "gt", l: "es-GT" },
  { n: "Spanish, Honduras", cc: "hn", l: "es-HN" },
  { n: "Spanish, LatinAmerica", cc: "es", l: "es-419" },
  { n: "Spanish, Mexico", cc: "mx", l: "es-MX" },
  { n: "Spanish, Nicaragua", cc: "ni", l: "es-NI" },
  { n: "Spanish, Panama", cc: "pa", l: "es-PA" },
  { n: "Spanish, Paraguay", cc: "py", l: "es-PY" },
  { n: "Spanish, Peru", cc: "pe", l: "es-PE" },
  { n: "Spanish, Puerto Rico", cc: "pr", l: "es-PR" },
  { n: "Spanish, United States", cc: "us", l: "es-US" },
  { n: "Spanish, Uruguay", cc: "uy", l: "es-UY" },
  { n: "Spanish, Venezuela", cc: "ve", l: "es-VE" },
  { n: "Sundanese", cc: "id", l: "su-ID" },
  { n: "Swahili", cc: "ke", l: "sw" },
  { n: "Swahili, Kenya", cc: "ke", l: "sw-KE" },
  { n: "Swahili, Tanzania", cc: "tz", l: "sw-TZ" },
  { n: "Swati", cc: "sz", l: "ss-ZA" },
  { n: "Swedish", cc: "se", l: "sv-SE" },
  { n: "Swedish, Finland", cc: "fi", l: "sv-FI" },
  { n: "Syriac", cc: "sy", l: "syc-SY" },
  { n: "Tagalog", cc: "ph", l: "tl-PH" },
  { n: "Tahitian", cc: "pf", l: "ty-PF" },
  { n: "Tajik", cc: "tj", l: "tg-TJ" },
  { n: "Tamil", cc: "in", l: "ta-IN" },
  { n: "Tatar", cc: "ru", l: "tt-RU" },
  { n: "Telugu", cc: "in", l: "te-IN" },
  { n: "Tem(Kotokoli)", cc: "tg", l: "kdh-KDH" },
  { n: "Thai", cc: "th", l: "th-TH" },
  { n: "Tibetan", cc: "bt", l: "bo-BT" },
  { n: "Tigrinya", cc: "er", l: "ti-ER" },
  { n: "Tsonga", cc: "za", l: "ts-ZA" },
  { n: "Tswana", cc: "bw", l: "tn-ZA" },
  { n: "Turkish", cc: "tr", l: "tr-TR" },
  { n: "Turkish, Cyprus", cc: "cy", l: "tr-CY" },
  { n: "Turkmen", cc: "tm", l: "tk-TM" },
  { n: "Ukrainian", cc: "ua", l: "uk-UA" },
  { n: "UpperSorbian", cc: "de", l: "hsb-DE" },
  { n: "Urdu, India", cc: "in", l: "ur-IN" },
  { n: "Urdu, Pakistan", cc: "pk", l: "ur-PK" },
  { n: "Uyghur", cc: "cn", l: "ug-CN" },
  { n: "Uzbek", cc: "uz", l: "uz-UZ" },
  { n: "Valencian", cc: "es", l: "val-ES" },
  { n: "Venda", cc: "za", l: "ve-ZA" },
  { n: "Venetian", cc: "it", l: "vec-IT" },
  { n: "Vietnse", cc: "vn", l: "vi-VN" },
  { n: "Walloon", cc: "be", l: "wa-BE" },
  { n: "Welsh", cc: "gb", l: "cy-GB" },
  { n: "Wolof", cc: "sn", l: "wo-SN" },
  { n: "Xhosa", cc: "za", l: "xh-ZA" },
  { n: "Yiddish", cc: "de", l: "yi-DE" },
  { n: "Yoruba", cc: "ng", l: "yo-NG" },
  { n: "Zeelandic", cc: "nl", l: "zea-ZEA" },
  { n: "Zulu", cc: "za", l: "zu-ZA" },
];
